Первая задача
Waranim/tests-tgbot pull request #9
Opened 2024-11-21 11:48 UTC by Waranim

2024-11-24 06:12 UTC, YaEtoTui commented
файлы .mvn не спрятаны. Так и должно быть?

2024-11-24 06:14 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/config/BotInit.java
> + * Инициализация телеграм бота
это не конфигурация. Даже если он компонент

2024-11-24 06:17 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/entity/QuestionEntity.java
> +
Много пробелов лишних

2024-11-24 06:18 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/entity/BaseEntity.java
> +public class BaseEntity {
Отличная идея) Чтобы не создавать по сто раз поле id ))

2024-11-24 06:21 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/entity/UserState.java
> +public enum UserState {
это не entity. Так почему он тут?

2024-11-24 06:22 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/repository/QuestionRepository.java
> +
Никита, у тебя с пробелами какие-то недопонимания) То где не надо есть они, то где они нужны -> их нет

2024-11-24 06:24 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +            case "/start":
Команды лучше сделать в виде объектов. Чтобы потом спокойно их использовать еще где-то, а если допустим захотите поправить, то в одном спокойно месте поменяете, а не в нескольких, и шансы получить баг будет меньше

2024-11-24 06:26 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    private static final Logger log = LoggerFactory.getLogger(UserService.class);
static запрещены в требованиях!

2024-11-24 06:27 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    public UserEntity get(Long id) {
просто get? Не информативно, переименуйте.

2024-11-24 06:28 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +        UserEntity user = userRepository.findById(id).orElse(null);
у вас есть так-то метод get() выше.

2024-11-24 06:32 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    public void setState(Long id, UserState state) {
Я ребят очень не понимаю писать геттеры и сеттеры у сервиса. Это он меняет состояние? Мне кажется нет. Вам надо их написать для тех сущностей, которые им пользуются. Вас домашняя работа про машину и назначение ничему что ли не научила?

2024-11-24 06:33 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    public QuestionEntity getCurrentQuestion(Long userId) {
Пытались написать javaDoc, и не дописали. Я же не приму ее пока не сделаете минимальные требования

2024-11-24 06:38 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +import org.telegram.telegrambots.meta.api.methods.send.SendMessage;
импорт нужен?

2024-11-24 06:39 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +
пробел лишний.

2024-11-24 06:41 UTC, YaEtoTui commented
Есть замечания

2024-11-24 07:08 UTC, YaEtoTui commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +import org.example.naumenteststgbot.repository.TestRepository;
Нужен import?

2024-11-24 07:10 UTC, YaEtoTui commented on src/test/java/org/example/naumenteststgbot/service/TestServiceTest.java
> +class TestServiceTest {
Тесты все не проходят

2024-11-27 10:45 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    public void setState(Long id, UserState state) {
но в этом сеттере помимо установления состояния имеется поиск пользователя по идентификатору и сохранение пользователя и сессии в базу данных

2024-11-27 11:17 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +
исправил

2024-11-27 11:17 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +import org.example.naumenteststgbot.repository.TestRepository;
не нужен, исправил

2024-11-28 07:10 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/config/BotInit.java
> + * Инициализация телеграм бота
Переместил

2024-11-28 07:13 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +            case "/start":
Обсудили это в телеграме. Мы решили не выносить их в константы, так как без static часть возможностей констант теряется

2024-11-28 07:13 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +import org.telegram.telegrambots.meta.api.methods.send.SendMessage;
Убрал

2024-12-01 14:13 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/entity/QuestionEntity.java
> +
исправил

2024-12-01 14:13 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/repository/QuestionRepository.java
> +
исправил

2024-12-01 19:45 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/entity/UserState.java
> +public enum UserState {
перенес

2024-12-01 19:46 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    private static final Logger log = LoggerFactory.getLogger(UserService.class);
убрал

2024-12-01 19:46 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    public UserEntity get(Long id) {
исправил

2024-12-01 19:46 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +        UserEntity user = userRepository.findById(id).orElse(null);
исправил

2024-12-01 19:47 UTC, GeorgiiMalishev commented on src/test/java/org/example/naumenteststgbot/service/TestServiceTest.java
> +class TestServiceTest {
исправил

2024-12-01 19:51 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    public QuestionEntity getCurrentQuestion(Long userId) {
исправлено

2024-12-02 15:01 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +            case "/start":
Да, тут я не досмотрел.

2024-12-02 15:03 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    public void setState(Long id, UserState state) {
Хорошо

2024-12-02 15:05 UTC, YaEtoTui commented on src/test/java/org/example/naumenteststgbot/service/TestServiceTest.java
> +class TestServiceTest {
TestServiceTest кстати интересное название)

2024-12-02 15:10 UTC, YaEtoTui commented on .gitignore
> +mvnw
Подскажи данные строчки нужны тебе? Если выше есть

2024-12-02 15:14 UTC, YaEtoTui commented
Моя замечания исправлены. 1-ое задание принято

2024-12-05 21:06 UTC, vpyzhyanov commented
> В целом дальше можно не проверять. Проект не рабочий

А нет, ошибочка вышла, ветка не та.

2024-12-05 21:13 UTC, vpyzhyanov requested changes
Проект без JavaDoc приниматься не будет!!!

![image](https://github.com/user-attachments/assets/2db8c101-f010-4bea-9216-53bab0273289)

2024-12-05 21:13 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/enums/UserState.java
> +public enum UserState {
Проект без JavaDoc приниматься не будет!!! На все элементы енама тоже нужен JavaDoc

2024-12-08 11:06 UTC, vpyzhyanov requested changes
Нет тестов на MessageHandler

Ну и поздравляю вас с вступлением в адепты тёмной стороны. Скоро за вами придёт отдел по борьбе с тьмой)))

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/config/BotConfig.java
> +public class BotConfig {
Этот класс `@Configuration` не является. Почитайте что такое `@Configuration`, зачем нужен, и используйте по назначению.

Удаляем этот класс, он не нужен. И нарушает инкапсуляцию. И главное - это вообще никому не нужно. Необходимые параметры можно инжектить сразу по назначению, т.е. в телеграмм бота. Все посредники выкидываем

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +    public TelegramBot(BotConfig config, CommandsHandler commandsHandler, MessageSender messageSender, MessageHandler messageHandler) {
Мастера однострочного программирования

Отличный способ скрыть тот факт, что вы на тёмной стороне. Ведь не будет видно вашего избыточного числа аргументов когда они все в одну строчку записаны

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +        this.messageSender = messageSender;
эмм..... это что вообще такое? И главное - зачем это надо?

Вы только прочувствуйте всю ситуацию. Создали интерфейс MessageSender, который используется только в TelegramBot, интерфейс реализует только TelegramBot (внутри себя). То есть создали совершенно бессмысленный интерфейс. Ладно бы просто его создали, но самое нелогичное - делать его аргументом конструктора TelegramBot. Который, между прочим не используется.

Удаляем ненужный конструктор. Удаляем MessageSender. TelegramBot и без него может отправить сообщение.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +    public TelegramBot(BotConfig config, CommandsHandler commandsHandler, MessageHandler messageHandler) {
`CommandsHandler commandsHandler, MessageHandler messageHandler`

Добро пожаловать в коллективную безответственность. Чем отличается команда от сообщения? Ничем! Даже оба являются текстом. Они даже через один объект приходят (Update).

На самом деле обработать сообщение от пользователя должен один класс.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +            if (update.getMessage().getText().startsWith("/")) {
ну и вот отличная демонстрация коллективной безответственности. Вот тут обработка команды, и ещё в двух классах commandsHandler и messageHandler. Целых 3 класса на одну функциональность.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TestService.java
> + * Сервис для обработки команд и сообщений, связанных с тестом
Даже в названии зафиксировали коллективную безотстветственность. Зачем тогда нужны CommandsHandler и MessageHandler?

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +    public CommandsHandler(HelpHandler helpHandler, UserService userService, TestService testService, QuestionService questionService) {
Какая тут тёмная сторона?

Оставлю вам на подумать как её исправить.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +            case "/start":
> Чтобы потом спокойно их использовать еще где-то

@YaEtoTui Егор, не надо толкать ребят на тёмную сторону. Если команда используется где-то ещё, то это сразу коллективная безответственность. За обработку команд должен отвечать только **ОДИН** класс.

И в тестах использовать их **запрещено**! Ведь тогда можно написать нечего не тестирующий тест.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +                replyText = testService.handleAdd(user.getId());
что-то явно пошло не так. Тут сервис, а до этого был Handler. Проблема с именами? Или тёмная сторона?

Хотя судя по тому, что testService вызывается несколько раз и получается сплошную строку на вход (то есть похоже сам её парсит), то на лицо тёмная сторона - перегруз по функционалу. Притом перегруз как в этом классе, а так и в TestService, который очевидно взял на себя не свою работу. Видимо не понимаете что такое сервисный слой.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +@Service
Если это не сервис, то это не `@Service`. Должен быть `@Component`

2024-12-08 11:06 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>hypersistence-utils-hibernate-63</artifactId>
будьте добры, покажите мне строчку в коде, в которой вы пользуетесь этой библиотекой

2024-12-08 11:06 UTC, vpyzhyanov commented on pom.xml
> +            <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
будьте добры, покажите мне строчку в коде, в которой вы пользуетесь этой библиотекой

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +    public SendMessage handleCommands(Update update) {
случилось страшное: одновременно коллективная безответственность и перегруз по функционалу. Вот зачем было тащить сюда зависимость от телеграмма? Весело и дружно выкидываем отсюда `Update` и убираем любые зависимости от телеграмма. Телеграмм не должен фигурировать нигде, кроме TelegramBot.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/MessageHandler.java
> +    public SendMessage handleMessage(Update update) {
похоже вы везде его потащили. Убираем

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/MessageHandler.java
> +@Service
Это не сервис!

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/MessageHandler.java
> +package org.example.naumenteststgbot.service;
Это не сервис!

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +@Service
Ну да, похоже вы вообще не представляете, что такое сервис.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +package org.example.naumenteststgbot.service;
Это не сервис!

Логичнее было бы выделить это в пакет `bot` или `telergam`

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/config/BotConfig.java
> +package org.example.naumenteststgbot.config;
1. Имя пакета - это часть структуры вашего кода, а не свалка из слов.
2. Имя пакета - не место для названия вашего проекта
3. Один пакет (директория) должна состоять из одного слова (есть редкие исключения, но это только для случаев, когда по другому нельзя)
4. Прошу убрать слово Naumen, содержание вашего проекта с Naumen никак не связано.
5. Прошу убрать слово Naumen из имени класса `NaumenTestsTgbotApplication` ровно по той же причине

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/init/BotInit.java
> +            botsApi.registerBot(bot);
Не очень критично, но коллективная безоствтветственность тут есть. TelegramBot в состоянии сам себя зарегистрировать. Нарушать инкапсуляцию для этого не нужно. TelegramBot можно закрыть для всех остальных, сделав соответствующий уровень видимости.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/entity/BaseEntity.java
> +        return 17;
О_о Это как понимать?

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/entity/UserEntity.java
> +    private Long id;
похоже вы посчитали, что BaseEntity - бесполезный класс

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/entity/UserEntity.java
> +        return 23;
О_о почему не 42?

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/enums/UserState.java
> +package org.example.naumenteststgbot.enums;
1. Не надо использовать множественное число в имени пакета. И ежу понятно, что в директории может находится несколько файлов.
2. Выбрано неудачное имя. Логичнее было выбрать предметную область, к которой относится класс. Вот например, вы же назвали пакет `entity`, а не `classes`. Почему? Потому что это сущности. А тут у вас лежат состояния. Логично было бы назвать пакет `state`
3. Вижу состояние, но не вижу класса, который бы этим состоянием управлял. Делаю вывод, что вы на тёмной стороне и какой-то из классов перегрузили ответственностью.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/repository/TestRepository.java
> +public interface TestRepository extends JpaRepository<TestEntity, Long> {
Проект без JavaDoc приниматься не будет!!!

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/repository/UserSessionRepository.java
> +public interface UserSessionRepository extends JpaRepository<UserSession, Long> {
Проект без JavaDoc приниматься не будет!!!

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +@Transactional
после того, как я рассказал как делать правильно. Делать неправильно - запрещено!

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +        this.answerRepository = answerRepository;
странно, что ответы отдельно от вопросов. И нужно работать с ними отдельно. Это особенно странно, т.к. в QuestionEntity все эти ответы подтягиваются. `(@OneToMany)`

Значит делаем вывод, что вы на тёмной стороне и тянете в этот класс лишние аргументы

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +    public QuestionService(QuestionRepository questionRepository, UserService userService, AnswerRepository answerRepository, TestService testService) {
мастера однострочного программирования

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +                return String.format("Введите название вопроса для теста “%s”", selectedTest.getTitle());
Ну всё понятно. Добро пожаловать на тёмную сторону.

1. Ни один сервис не общается с пользователем, значит либо это вовсе не сервис, либо класс перегружен функционалом
2. Коллективная безоствтветственность - общаться с пользователем - это работа другого класса.

Вы уж определитесь, либо вы обрабатываете команду от пользователя и общаетесь с ним, либо делаете сервис для управления вопросами. Сейчас класс сильно перегружен

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +    public String handleAddQuestion(Long userId, String message) {
что интересно. Вы зачем-то разделили CommandsHandler и MessageHandler, но в этом классе вы решили их объединить в один. Противоречите сами себе.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TestService.java
> +    @Transactional
После того, как я рассказал как делать правильно, неправильно делать запрещено!

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/TestService.java
> +                Вы выбрали тест “%s”. Что вы хотите изменить?
всё то же самое. Вмешали сервис и обработку команд. Надо их разделить

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> + * Предостволяет функционал добавления, редактирования, просмотра и удаления вопросов
Это неправда. В классе нет таких методов. Всё, что есть:

![image](https://github.com/user-attachments/assets/de8f9df9-fe38-4606-bf53-fda63a18b733)

Возможность создать вопрос, добавить ответ и установить правильность. Только этого сделать нельзя, т.к. они приватные.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +@Transactional
убираем

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    @Transactional
1. Аннотация лишняя, т.к. вы навесили её на класс
2. Неправильно делать - запрещено!

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +        if (user == null) return;
мастера однострочного программирования. Ваша цель сделать нечитаемый код?

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +        user.getSession().setCurrentTest(testEntity);
Не надо вводить в заблуждение, это `UserSession`, поэтому метод должен называться `setUserSession`

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    private final UserSessionRepository userSessionRepository;
Используете 2 репозитория для одного сервиса. Значит очевидно, что вы на тёмной стороне, перегрузили класс функционалом. Работа с сессиями пользователя должна быть отдельно.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/entity/UserSession.java
> + * Текущая сессия пользователя
хорошо бы пояснить, что такое сессия пользователя. А то, судя по полям и методам, это вообще не сессию не похоже

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/CommandsHandlerTest.java
> +        when(message.getChatId()).thenReturn(12345L);
непонятно зачем сами себе осложнили жизнь этими сложными конструкциями

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/CommandsHandlerTest.java
> +        SendMessage response = commandHandler.handleCommands(update);
убрать отсюда `SendMessage`, не портите себе жизнь

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        ReflectionTestUtils.setField(question, "id", questionId);
убираем все эти жёсткие хаки! Учитесь пользоваться конструкторами

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        verify(answerRepository, times(timesSaved)).save(any(AnswerEntity.class));
Я учил делать не так. А как? Как правильно делается проверка?

> Добавляет ответ и проверяет его сохранение

Неправда, "его" сохранение не проверяется. А проверяется просто сам факт сохранения, неважно чего. Вот что случается, когда не делаешь так, как преподаватель учит. Написали проверку, которая только выглядит нормальной, но по факту вообще ничего не проверяет.

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        verify(answerRepository, times(2)).save(any(AnswerEntity.class));
ничего не проверяет

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        userSession.setState(UserState.SET_CORRECT_ANSWER);
Что логика делает в тесте? Разве не ваш сервис должен этим заниматься?

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        userSession.setState(UserState.DEFAULT);
вот в конце теста этот метод выглядит особенно дико. Зачем он вам нужен?

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/TelegramBotTest.java
> +class TelegramBotTest {
Ого, тест телеграмм бота. Забавно)))

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/TelegramBotTest.java
> +        String username = telegramBot.getBotUsername();
то есть вы не доверяете общему интерфейсу и библиотеке в целом? Если не доверяете, то пишите свою

2024-12-08 11:06 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/TelegramBotTest.java
> +        SendMessage expectedMessage = new SendMessage("12345", "Я вас не понимаю, для справки используйте /help");
А, ну да, у вас же логика в этом классе, которой быть не должно.

2024-12-08 11:10 UTC, YaEtoTui commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +            case "/start":
Я, Вячеслав, понял

2024-12-17 11:12 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/enums/UserState.java
> +public enum UserState {
Написали

2024-12-17 11:13 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/config/BotConfig.java
> +public class BotConfig {
Удалили

2024-12-17 11:13 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +    public TelegramBot(BotConfig config, CommandsHandler commandsHandler, MessageSender messageSender, MessageHandler messageHandler) {
Исправили

2024-12-17 11:13 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +        this.messageSender = messageSender;
Удалили

2024-12-17 11:14 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +    public TelegramBot(BotConfig config, CommandsHandler commandsHandler, MessageHandler messageHandler) {
Переработали логику, теперь есть только MessageHandler

2024-12-17 11:15 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +@Transactional
Убрал транзакцию

2024-12-17 11:17 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +        this.answerRepository = answerRepository;
Убрал репозиторий ответов, в методе где использовался answerRepository, теперь используется questionRepository

2024-12-17 11:17 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +    public QuestionService(QuestionRepository questionRepository, UserService userService, AnswerRepository answerRepository, TestService testService) {
исправил

2024-12-17 11:18 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +                return String.format("Введите название вопроса для теста “%s”", selectedTest.getTitle());
Вынес не относящуюся к сервису логику в отдельные классы

2024-12-17 11:18 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +    public String handleAddQuestion(Long userId, String message) {
исправили

2024-12-17 11:18 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> + * Предостволяет функционал добавления, редактирования, просмотра и удаления вопросов
Переделал javaDoc

2024-12-17 11:18 UTC, Waranim commented on pom.xml
> +            <artifactId>hypersistence-utils-hibernate-63</artifactId>
Библиотека не использовалась, убрали

2024-12-17 11:18 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        ReflectionTestUtils.setField(question, "id", questionId);
переделал тесты

2024-12-17 11:18 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        verify(answerRepository, times(timesSaved)).save(any(AnswerEntity.class));
переделал тесты

2024-12-17 11:19 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        verify(answerRepository, times(2)).save(any(AnswerEntity.class));
переделал тесты

2024-12-17 11:19 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +@Service
Заменили на подходящую аннотацию

2024-12-17 11:19 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        userSession.setState(UserState.SET_CORRECT_ANSWER);
в новых тестах логика не используется

2024-12-17 11:19 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +package org.example.naumenteststgbot.service;
Вынесли в пакет telegram

2024-12-17 11:20 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        userSession.setState(UserState.DEFAULT);
Исправил, больше не используется

2024-12-17 11:20 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/config/BotConfig.java
> +package org.example.naumenteststgbot.config;
Переименовали пакет и убрали упоминание Naumen в названиях

2024-12-17 11:22 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +    public CommandsHandler(HelpHandler helpHandler, UserService userService, TestService testService, QuestionService questionService) {
Перегруженный функционалом класс, исправили тем, что сделали цепочку обработчиков, в котором каждый отвечает за свою команду или состояние.

2024-12-17 11:23 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/init/BotInit.java
> +            botsApi.registerBot(bot);
Удалили ненужный класс, перенесли регистрацию в TelegramBot, изменили область видимости TelegramBot

2024-12-17 11:23 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/TestService.java
> + * Сервис для обработки команд и сообщений, связанных с тестом
исправили, разделили логику работы с тестами и общение с пользователями

2024-12-17 11:23 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/entity/BaseEntity.java
> +        return 17;
Исправили

2024-12-17 11:24 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/entity/UserEntity.java
> +    private Long id;
Переименовали переменную для лучшего понимания, почему не используется BaseEntity

2024-12-17 11:24 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/TelegramBot.java
> +            if (update.getMessage().getText().startsWith("/")) {
исправили, остался только MessageHandler, который обрабатывает все входящие сообщения

2024-12-17 11:24 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/entity/UserEntity.java
> +        return 23;
Исправили

2024-12-17 11:25 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +                replyText = testService.handleAdd(user.getId());
исправили, теперь только обработчики принимают сообщения

2024-12-17 11:26 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/TestService.java
> +    @Transactional
Убрали транзакцию

2024-12-17 11:26 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +@Transactional
Убрали

2024-12-17 11:26 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +@Service
CommandsHandler больше нет, а в MessageHandler исправили

2024-12-17 11:27 UTC, Waranim commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    @Transactional
Исправили

2024-12-17 11:27 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/CommandsHandler.java
> +    public SendMessage handleCommands(Update update) {
исправили, теперь обработчик принимает строку и идентификатор, и отдает строку.

2024-12-17 11:28 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/MessageHandler.java
> +@Service
исправили

2024-12-17 11:29 UTC, Waranim commented on src/test/java/org/example/naumenteststgbot/service/TelegramBotTest.java
> +class TelegramBotTest {
Удалили

2024-12-17 11:29 UTC, orgmange commented on src/main/java/org/example/naumenteststgbot/service/MessageHandler.java
> +package org.example.naumenteststgbot.service;
перенесли

2024-12-17 11:29 UTC, Waranim commented on src/test/java/org/example/naumenteststgbot/service/TelegramBotTest.java
> +        String username = telegramBot.getBotUsername();
Доверяем, тест удалили

2024-12-17 11:30 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/enums/UserState.java
> +package org.example.naumenteststgbot.enums;
исправили, перенесли в state, сделали сервис для состояний

2024-12-17 11:30 UTC, Waranim commented on src/test/java/org/example/naumenteststgbot/service/TelegramBotTest.java
> +        SendMessage expectedMessage = new SendMessage("12345", "Я вас не понимаю, для справки используйте /help");
Тест был удалён

2024-12-17 11:30 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/repository/TestRepository.java
> +public interface TestRepository extends JpaRepository<TestEntity, Long> {
написали

2024-12-17 11:30 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/repository/UserSessionRepository.java
> +public interface UserSessionRepository extends JpaRepository<UserSession, Long> {
написали

2024-12-17 11:32 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/TestService.java
> +                Вы выбрали тест “%s”. Что вы хотите изменить?
разделили

2024-12-17 11:33 UTC, Waranim commented on pom.xml
> +            <artifactId>jackson-module-jakarta-xmlbind-annotations</artifactId>
Библиотека не использовалась, убрали

2024-12-17 11:36 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +        user.getSession().setCurrentTest(testEntity);
перенесли метод в SessionService

2024-12-17 11:37 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/entity/UserSession.java
> + * Текущая сессия пользователя
Переименовали в UserContext

2024-12-17 11:40 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/MessageHandler.java
> +    public SendMessage handleMessage(Update update) {
убрали

2024-12-17 11:41 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    private final UserSessionRepository userSessionRepository;
Исправили

2024-12-17 11:42 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +    private final UserSessionRepository userSessionRepository;
исправили, вынесли логику работы с контекстом(сессией) и состояниями в отдельные сервисы

2024-12-17 11:44 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/CommandsHandlerTest.java
> +        SendMessage response = commandHandler.handleCommands(update);
Исправили

2024-12-17 11:47 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/CommandsHandlerTest.java
> +        when(message.getChatId()).thenReturn(12345L);
Переделали тесты

2024-12-17 12:01 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/UserService.java
> +        if (user == null) return;
исправили

2024-12-17 20:14 UTC, vpyzhyanov commented
> Нет тестов на MessageHandler

Тестов не появилось!

2024-12-17 20:16 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/config/BotConfig.java
> +public class BotConfig {
> нарушает инкапсуляцию

С инкапсуляцией какая-то проблема. Как ещё не было, так и нет. Метод `org.example.bot.telegram.TelegramBot#init` публичный и никем не вызывается.

2024-12-17 20:33 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +        this.answerRepository = answerRepository;
Не полностью убрали, он по прежнему присутствует

![image](https://github.com/user-attachments/assets/cd0297e3-ba9e-4878-9591-92380a9e0745)

2024-12-17 20:35 UTC, vpyzhyanov commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +                return String.format("Введите название вопроса для теста “%s”", selectedTest.getTitle());
Не исправлено! 

![image](https://github.com/user-attachments/assets/9a4d84c2-61ec-49b9-a621-c2f5e6d60f55)

2024-12-17 20:44 UTC, vpyzhyanov commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        verify(answerRepository, times(timesSaved)).save(any(AnswerEntity.class));
Игнор вопросов плохо отражается как на баллах, так и на отношении к вам, учитывайте это, пожалуйста

2024-12-17 21:12 UTC, vpyzhyanov requested changes
Не все ошибки исправлены. И неработающий проект приниматься не будет!

![image](https://github.com/user-attachments/assets/575315b4-cb6e-456c-ba6c-c983a766a97d)

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/handler/MessageHandler.java
> +                .filter(processor -> processor.canProcess(userId, message))
какова сложность этого алгоритма?

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/processor/AbstractCommandProcessor.java
> +    public boolean canProcess(Long userId, String message) {
Надо добавить `final`

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/processor/AbstractCommandProcessor.java
> +    protected String extractCommand(String message) {
Надо добавить `final`

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/processor/AbstractStateProcessor.java
> +    public boolean canProcess(Long userId, String message) {
Надо добавить `final`

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/service/ContextService.java
> +     * @return контекст пользователя или null, если пользователь не найден
в таких случаях лучше использовать `Optional`, это надёжнее и удобнее. null это всегда потенциальный NPE

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/service/ContextService.java
> +     * @return текущий вопрос или null, если пользователь не найден
в таких случаях лучше использовать `Optional`, это надёжнее и удобнее

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/service/ContextService.java
> +     * @return текущий тест или null, если пользователь не найден
аналогично

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/service/QuestionService.java
> +        return String.format("Вариант ответа %s назначен правильным.", optionIndex);
замечание не исправлено!

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/service/QuestionService.java
> +        return questionRepository.findById(id).orElse(null);
в таких случаях лучше использовать `Optional`, это надёжнее и удобнее

Тут он даже уже есть готовый. Просто не надо было его выкидывать.

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/service/StateService.java
> +     * @return текущее состояние или null, если пользователь не найден
в таких случаях лучше использовать `Optional`, это надёжнее и удобнее

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/service/TestService.java
> +        return testRepository.findById(id).orElse(null);
в таких случаях лучше использовать `Optional`, это надёжнее и удобнее

И ниже тоже

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/service/UserService.java
> +        userEntity.setContext(new UserContext(id));
проще было конструктор создать подходящий

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/telegram/TelegramBot.java
> +    public void init() {
нарушена инкапсуляция

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/util/Util.java
> +    public String testToString(TestEntity test) {
Добро пожаловать в коллективную безоствтветственность. Этот метод используется в одном единственном месте. Это вас должно было насторожить. Вот где он используется, там и должен быть определён. Убираем его отсюда

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/util/Util.java
> +                if(answer.isCorrect()) correctAnswer = answer;
снова однострочное программирование. Ну что за мания такая!?

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/util/Util.java
> +    public String testsListToString(List<TestEntity> tests) {
1. Не стоит все утилитарные методы скидывать в одну кучу. Их можно разделить по категориям. Например методы для работы с тестами можно поместить в `TestUtils`. Методы работы с числами в `NumberUtils`. 
2. `testsList` - 2 раза указывается на то, что тут множественное число. Хватит и одного.

2024-12-17 21:12 UTC, vpyzhyanov commented on src/main/java/org/example/bot/util/Util.java
> +    public boolean isNumber(String number) {
возможно этот метод может быть частью CommandProcessor

2024-12-17 21:12 UTC, vpyzhyanov commented on src/test/java/org/example/bot/service/TestMessageProcessorTest.java
> +class TestMessageProcessorTest {
Не надо вводить в заблуждение. Тест проверяет не MessageProcessor, а другой класс. Какой?

И не надо 2 раза писать слово Test, тем более у оригинала `MessageProcessor` нет слова Test

2024-12-17 21:12 UTC, vpyzhyanov commented on src/test/java/org/example/bot/service/TestMessageProcessorTest.java
> +        prepareTestData();
слышали когда-нибудь про `@BeforeEach`? Это как раз тот случай, когда им стоит воспользоваться

2024-12-17 21:12 UTC, vpyzhyanov commented on src/test/java/org/example/bot/service/TestMessageProcessorTest.java
> +    void clearMocks() {
очистка всегда делается в конце выполнения, а не в начале

2024-12-18 19:08 UTC, trofim20 commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +                return String.format("Введите название вопроса для теста “%s”", selectedTest.getTitle());
Исправил

2024-12-18 19:11 UTC, trofim20 commented on src/test/java/org/example/naumenteststgbot/service/QuestionServiceTest.java
> +        verify(answerRepository, times(timesSaved)).save(any(AnswerEntity.class));
Виноват, правильно нужно было сделать было так, что бы проверялся конкретный экземпляр сущности

2024-12-18 19:12 UTC, trofim20 commented on src/main/java/org/example/bot/processor/AbstractCommandProcessor.java
> +    protected String extractCommand(String message) {
исправили

2024-12-18 19:12 UTC, trofim20 commented on src/main/java/org/example/bot/processor/AbstractStateProcessor.java
> +    public boolean canProcess(Long userId, String message) {
исправили

2024-12-18 19:12 UTC, trofim20 commented on src/main/java/org/example/bot/service/QuestionService.java
> +        return String.format("Вариант ответа %s назначен правильным.", optionIndex);
проглядел, исправил

2024-12-18 19:12 UTC, trofim20 commented on src/main/java/org/example/bot/service/QuestionService.java
> +        return questionRepository.findById(id).orElse(null);
исправил

2024-12-18 19:13 UTC, trofim20 commented on src/main/java/org/example/bot/util/Util.java
> +                if(answer.isCorrect()) correctAnswer = answer;
исправил

2024-12-18 19:14 UTC, trofim20 commented on src/main/java/org/example/bot/processor/AbstractCommandProcessor.java
> +    public boolean canProcess(Long userId, String message) {
исправил

2024-12-18 19:18 UTC, GeorgiiMalishev commented on src/main/java/org/example/bot/handler/MessageHandler.java
> +                .filter(processor -> processor.canProcess(userId, message))
в данной реализации сложность O(n). Можно было бы сделать 2 HashMap с командами и состояниями в качестве ключей, но тогда бы ухудшилась расширяемость обработчиков, и сам messageHandler был бы перегружен лишним функционалом.

2024-12-18 19:19 UTC, orgmange commented on src/test/java/org/example/bot/service/TestMessageProcessorTest.java
> +    void clearMocks() {
исправлено, теперь очистка выполняется после каждого теста

2024-12-18 19:19 UTC, GeorgiiMalishev commented on src/test/java/org/example/bot/service/TestMessageProcessorTest.java
> +        prepareTestData();
исправлено, теперь на этом методе есть аннотация @BeforeEach

2024-12-18 19:20 UTC, GeorgiiMalishev commented on src/test/java/org/example/bot/service/TestMessageProcessorTest.java
> +        prepareTestData();
исправлено

2024-12-18 19:22 UTC, GeorgiiMalishev commented on src/test/java/org/example/bot/service/TestMessageProcessorTest.java
> +class TestMessageProcessorTest {
Этот класс проверяет обработчики, связанные с добавлением, редактированием, просмотром и удалением теста.
Для MessageProcessor сделали свой класс с тестами

2024-12-18 19:23 UTC, trofim20 commented on src/main/java/org/example/bot/service/ContextService.java
> +     * @return контекст пользователя или null, если пользователь не найден
теперь используем Optional

2024-12-18 19:23 UTC, trofim20 commented on src/main/java/org/example/bot/service/ContextService.java
> +     * @return текущий вопрос или null, если пользователь не найден
сделали

2024-12-18 19:23 UTC, trofim20 commented on src/main/java/org/example/bot/service/ContextService.java
> +     * @return текущий тест или null, если пользователь не найден
сделали

2024-12-18 19:24 UTC, trofim20 commented on src/main/java/org/example/bot/service/StateService.java
> +     * @return текущее состояние или null, если пользователь не найден
теперь используем Optional

2024-12-18 19:24 UTC, GeorgiiMalishev commented on src/main/java/org/example/bot/util/Util.java
> +    public boolean isNumber(String number) {
К сожалению не могу перенести, так как isNumber() используется не только в обработчиках команд, но и в обработчиках состояний

2024-12-18 19:24 UTC, trofim20 commented on src/main/java/org/example/bot/service/TestService.java
> +        return testRepository.findById(id).orElse(null);
сделали

2024-12-18 19:24 UTC, GeorgiiMalishev commented on src/main/java/org/example/bot/util/Util.java
> +    public String testsListToString(List<TestEntity> tests) {
Разделили по категориям, переименовали дублирующиеся названия

2024-12-18 19:25 UTC, GeorgiiMalishev commented on src/main/java/org/example/bot/util/Util.java
> +    public String testToString(TestEntity test) {
перенесли туда, где он используется

2024-12-18 19:27 UTC, GeorgiiMalishev commented on src/main/java/org/example/naumenteststgbot/service/QuestionService.java
> +        this.answerRepository = answerRepository;
Удалили

2024-12-19 14:54 UTC, Waranim commented on src/main/java/org/example/bot/service/UserService.java
> +        userEntity.setContext(new UserContext(id));
Создали

2024-12-19 14:54 UTC, Waranim commented on src/main/java/org/example/bot/telegram/TelegramBot.java
> +    public void init() {
Исправили

2024-12-19 18:02 UTC, vpyzhyanov commented on src/main/java/org/example/bot/handler/MessageHandler.java
> +                .filter(processor -> processor.canProcess(userId, message))
> но тогда бы ухудшилась расширяемость обработчиков, и сам messageHandler был бы перегружен лишним функционалом.

Если всё правильно сделать, то такого не произойдёт. А так да, мысль использовать HashMap правильная

2024-12-19 18:17 UTC, vpyzhyanov commented on src/main/java/org/example/bot/util/Util.java
> +                if(answer.isCorrect()) correctAnswer = answer;
Открою вам тайну: строчки бесплатные. А нечитаемый код очень дорого стоит.

2024-12-19 18:31 UTC, vpyzhyanov approved these changes
Задача принята.

- ООП: 5 баллов
- Git: 3 балла

2024-12-19 18:34 UTC, merged